const challengeResult1 = [
  { 'País': 'Argentina', 'Status Inclusão': 'não incluído' },
  { 'País': 'Australia', 'Status Inclusão': 'não incluído' },
  { 'País': 'Belgium', 'Status Inclusão': 'incluído' },
  { 'País': 'Brazil', 'Status Inclusão': 'não incluído' },
  { 'País': 'Canada', 'Status Inclusão': 'não incluído' },
  { 'País': 'China', 'Status Inclusão': 'não incluído' },
  { 'País': 'Denmark', 'Status Inclusão': 'incluído' },
  { 'País': 'Egypt', 'Status Inclusão': 'não incluído' },
  { 'País': 'France', 'Status Inclusão': 'incluído' },
  { 'País': 'Germany', 'Status Inclusão': 'incluído' },
  { 'País': 'HongKong', 'Status Inclusão': 'não incluído' },
  { 'País': 'India', 'Status Inclusão': 'não incluído' },
  { 'País': 'Israel', 'Status Inclusão': 'não incluído' },
  { 'País': 'Italy', 'Status Inclusão': 'incluído' },
  { 'País': 'Japan', 'Status Inclusão': 'não incluído' },
  { 'País': 'Kuwait', 'Status Inclusão': 'não incluído' },
  { 'País': 'Mexico', 'Status Inclusão': 'não incluído' },
  { 'País': 'Netherlands', 'Status Inclusão': 'incluído' },
  { 'País': 'Nigeria', 'Status Inclusão': 'não incluído' },
  { 'País': 'Singapore', 'Status Inclusão': 'não incluído' },
  { 'País': 'Switzerland', 'Status Inclusão': 'incluído' },
  { 'País': 'United Kingdom', 'Status Inclusão': 'incluído' },
  { 'País': 'United States of America', 'Status Inclusão': 'não incluído' },
  { 'País': 'Zambia', 'Status Inclusão': 'não incluído' },
  { 'País': 'Zimbabwe', 'Status Inclusão': 'não incluído' },
];

module.exports = challengeResult1;
